// bonus-comparison-with-react/Counter.tsx
import { useState, useEffect } from 'react';
import fetchCount from '../fetchCount';
import ControlBar from '../ControlBar';

interface Props {
  limit: number;
  alertMessageOnLimit?: string;
}

function Counter({ limit, alertMessageOnLimit = 'can not go any higher' }: Props) {
  const [count, useCount] = useState<number | null>(null);

  useEffect(() => {
    fetchCount((initialCount) => {
      setCount(initialCount);
    });
  }, []);

  function addCount(num: number) {
    if (count !== null) {
      if (count >= limit) {
        alert(alertMessageOnLimit);
      } else {
        setCount(num);
      }
    }
  }

  return (
    <div>
      <p>{count}</p>
      <ControlBar addCount={addCount} resetCount={() => setCount(0)} />
    </div>
  );
}

export default Counter;

// bonus-comparison-with-react/Counter.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import fetchCount from '../fetchCount';
import ControlBar from '../ControlBar.vue';

interface Props {
  limit: number;
  alertMessageOnLimit?: string;
}

const props = withDefaults(defineProps<Props>(), {
  alertMessageOnLimit: 'can not go any higher',
});

const count = ref<number | null>(null);

onMounted(() => {
  fetchCount((initialCount) => {
    count.value = initialCount;
  });
});

function addCount(num: number) {
  if (count.value !== null) {
    if (count.value >= props.limit) {
      alert(props.alertMessageOnLimit);
    } else {
      count.value += num;
    }
  }
}
</script>

<template>
  <p>{{ count }}</p>
  <control-bar @add-count="addCount($event)" @reset-count="resetCount" />
</template>
