// my-app/src/components/Counter.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import fetchCount from '../services/fetchCount';

interface Props {
  limit: number;
  alertMessageOnLimit?: string;
}

const props = withDefaults(defineProps<Props>(), {
  alertMessageOnLimit: 'can not go any higher',
});

/**
 * Note: props can be received like Vue 2 too insteaf of Pure Typescript Annotation:
 *
 * const props = defineProps({
 *  limit: { type: Number, required: true },
 *  alertMessageOnLimit: { type: String, required: true },
 * })
 */

// Note: w/ fetchCount example, we saw wront Type Inference (and force manually the correct way)
const count = ref<number | null>(null);

// Note: for demonstration, this computed value return a value
const nextCount = computed(() => {
  if (count.value !== null) {
    return count.value + 1;
  }
  return null;
});

onMounted(() => {
  fetchCount((initialCount) => {
    count.value = initialCount;
  });
});

function addCount(num: number) {
  if (count.value !== null) {
    if (count.value >= props.limit) {
      alert(props.alertMessageOnLimit);
    } else {
      count.value += num;
    }
  }
}
</script>

<template>
  <p>{{ count }}</p>
  <button @click="addCount(1)">Add</button>
</template>

// bonus-comparison-with-react/Counter.tsx
import { useState, useEffect } from 'react';
import fetchCount from '../fetchCount';
import ControlBar from '../ControlBar';

interface Props {
  limit: number;
  alertMessageOnLimit?: string;
}

function Counter({ limit, alertMessageOnLimit = 'can not go any higher' }: Props) {
  const [count, useCount] = useState<number | null>(null);

  useEffect(() => {
    fetchCount((initialCount) => {
      setCount(initialCount);
    });
  }, []);

  function addCount(num: number) {
    if (count !== null) {
      if (count >= limit) {
        alert(alertMessageOnLimit);
      } else {
        setCount(num);
      }
    }
  }

  return (
    <div>
      <p>{count}</p>
      <ControlBar addCount={addCount} resetCount={() => setCount(0)} />
    </div>
  );
}

export default Counter;
